self_play_cfg:
  eval_pretrained_agents:
    # - /home/borakargi/Personal/models/TD3-gaussian-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-21-21-39-54
    - /home/borakargi/Personal/models/TD3-gaussian-default-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-25-09-03-41
    # - /home/borakargi/Personal/models/TD3-pink-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-01-02-28
    # - /home/borakargi/Personal/models/TD3-golden-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-10-09-54