algorithm_cfg:
  batch_size: 128
  # Layer Norm arguments
  use_layer_norm: False
  layer_norm_eps: 0.00001
  learning_starts: 50000
  n_eval_episodes: 100
  max_steps: 250
  action_noise: 0.1
  noise: "brown"
  policy_delay: 2
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  opponent_noise_type: "none"
  opponent_noise: 0.05
  beta: 0.4 # Starting beta value 
log_cfg:
  log_dir: /home/borakargi/Personal/logs
  log_filename_suffix: td3-pink-per-ln
  model_name: model
optim_cfg:
  actor_config:
    lr: 0.0003
    # weight_decay: 0.00001
  critic_config:
    lr: 0.0003
reward_cfg:
  winner: 10.0
  reward_touch_puck: 0.0
  reward_closeness_to_puck: 1.0
  reward_puck_direction: 0.0
replay_buffer_cfg:
  type: "simple"
  max_size: 1000000
  alpha: 0.6 # Alpha value for prioritized replay buffer
self_play_cfg:
  self_train: False
  self_playing_threshold: 0.9
  self_training_max_agents: 5
  start_pretrained: 1000000
  # train_pretrained_agents:
  #     - /home/borakargi/Personal/models/TD3-gaussian-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-21-21-39-54
  #     - /home/borakargi/Personal/models/TD3-pink-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-01-02-28
  #     - /home/borakargi/Personal/models/TD3-golden-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-10-09-54
  # eval_pretrained_agents:
  #     - /home/borakargi/Personal/models/TD3-gaussian-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-21-21-39-54
  #     - /home/borakargi/Personal/models/TD3-pink-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-01-02-28
  #     - /home/borakargi/Personal/models/TD3-golden-dense-ep_5e6-lr3e-4-gamma-0.95-b128_Hockey-v0_0_2025-02-22-10-09-54